// Class definitions. Names from EN + DE wikis.
const CLASSES = {
  warrior_body:      { name: { en: "Warrior · Body",       de: "Krieger · Körper" },     strCoef: 2, weapon: "sword_2h", magic: false },
  warrior_mental:    { name: { en: "Warrior · Mental",     de: "Krieger · Geist" },      strCoef: 2, weapon: "sword_1h", magic: false },
  ninja_blade:       { name: { en: "Ninja · Blade",        de: "Ninja · Klinge" },       strCoef: 2, weapon: "dagger",   magic: false },
  ninja_bow:         { name: { en: "Ninja · Bow",          de: "Ninja · Bogen" },        strCoef: 2, weapon: "bow",      magic: false },
  sura_weapon:       { name: { en: "Sura · Weapon",        de: "Sura · Waffe" },         strCoef: 2, weapon: "sword_1h", magic: false },
  sura_black_magic:  { name: { en: "Sura · Black Magic",   de: "Sura · Schwarze Magie" },strCoef: 1, weapon: "sword_1h", magic: true  },
  shaman_dragon:     { name: { en: "Shaman · Dragon",      de: "Schamanin · Drache" },   strCoef: 1, weapon: "fan",      magic: true  },
  shaman_healing:    { name: { en: "Shaman · Healing",     de: "Schamanin · Heilung" },  strCoef: 1, weapon: "bell",     magic: true  },
  lycan:             { name: { en: "Lycan",                de: "Lykaner" },              strCoef: 2, weapon: "claw",     magic: false },
};

const REFINE_MULT = [1.00, 1.03, 1.06, 1.09, 1.12, 1.16, 1.20, 1.25, 1.30, 1.40];

// Weapon presets — names taken from the Metin2 wiki weapons categories.
// Stats here are approximate +0 values inferred from tier — open the wiki entry
// for any weapon to confirm exact numbers. Edit freely.
const WEAPONS = {
  sword_1h: [
    { id: "sword",          name: { en: "Sword",              de: "Schwert" },             level: 1,   min: 4,   max: 7,   magic: 0 },
    { id: "battle_sword",   name: { en: "Battle Sword",       de: "Schlachtschwert" },     level: 6,   min: 12,  max: 16,  magic: 0 },
    { id: "long_sword",     name: { en: "Long Sword",         de: "Langschwert" },         level: 12,  min: 22,  max: 30,  magic: 0 },
    { id: "broad_sword",    name: { en: "Broad Sword",        de: "Breitschwert" },        level: 18,  min: 36,  max: 48,  magic: 0 },
    { id: "sting_sword",    name: { en: "Sting Sword",        de: "Stichschwert" },        level: 22,  min: 48,  max: 62,  magic: 0 },
    { id: "silver_sword",   name: { en: "Silver Sword",       de: "Silberschwert" },       level: 28,  min: 64,  max: 82,  magic: 0 },
    { id: "orchid_sword",   name: { en: "Orchid Sword",       de: "Orchideenschwert" },    level: 32,  min: 78,  max: 98,  magic: 0 },
    { id: "bastard_sword",  name: { en: "Bastard Sword",      de: "Anderthalbhänder" },    level: 36,  min: 92,  max: 115, magic: 0 },
    { id: "rune_sword",     name: { en: "Rune Sword",         de: "Runenschwert" },        level: 40,  min: 108, max: 132, magic: 0 },
    { id: "nymph_sword",    name: { en: "Nymph Sword",        de: "Nymphenschwert" },      level: 48,  min: 138, max: 168, magic: 0 },
    { id: "half_moon",      name: { en: "Half Moon Sword",    de: "Halbmondschwert" },     level: 52,  min: 152, max: 185, magic: 0 },
    { id: "full_moon",      name: { en: "Full Moon Sword",    de: "Sichelschwert" },       level: 56,  min: 168, max: 202, magic: 0 },
    { id: "poison_sword",   name: { en: "Poison Sword",       de: "Giftschwert" },         level: 60,  min: 184, max: 220, magic: 0 },
    { id: "triton_sword",   name: { en: "Triton Sword",       de: "Tritonschwert" },       level: 64,  min: 200, max: 238, magic: 0 },
    { id: "bloody_sword",   name: { en: "Bloody Sword",       de: "Blutiges Schwert" },    level: 68,  min: 215, max: 256, magic: 0 },
    { id: "serpent_sword",  name: { en: "Serpent Sword",      de: "Schlangenschwert" },    level: 72,  min: 232, max: 275, magic: 0 },
    { id: "flying_wizard",  name: { en: "Flying Wizard Sword",de: "Schwert des fliegenden Magiers" }, level: 75, min: 245, max: 290, magic: 0 },
    { id: "zodiac_sword",   name: { en: "Zodiac Sword",       de: "Tierkreisschwert" },    level: 80,  min: 262, max: 308, magic: 0 },
    { id: "crescent_sword", name: { en: "Crescent Sword",     de: "Mondschein-Klinge" },   level: 85,  min: 280, max: 328, magic: 0 },
    { id: "gloom_dragon_sword", name: { en: "Gloom Dragon Sword", de: "Dunkeldrachenschwert" }, level: 90, min: 298, max: 348, magic: 0 },
    { id: "soul_stealer",   name: { en: "Soul Stealing Blade",de: "Seelendieb" },          level: 92,  min: 308, max: 360, magic: 0 },
    { id: "steel_song",     name: { en: "Steel Song",         de: "Stahlgesang" },         level: 95,  min: 320, max: 372, magic: 0 },
    { id: "burning_fury",   name: { en: "Burning Fury",       de: "Sengende Wut" },        level: 100, min: 340, max: 395, magic: 0 },
    { id: "barbarian_sword",name: { en: "Barbarian Sword",    de: "Barbarenschwert" },     level: 102, min: 350, max: 405, magic: 0 },
    { id: "destiny_blade",  name: { en: "Destiny Blade",      de: "Schicksalsklinge" },    level: 105, min: 370, max: 430, magic: 0 },
    { id: "requiem",        name: { en: "Requiem",            de: "Requiem" },             level: 108, min: 388, max: 448, magic: 0 },
    { id: "askalahel",      name: { en: "Askalahel",          de: "Askalahel" },           level: 110, min: 400, max: 465, magic: 0 },
    { id: "durendals_avenger", name: { en: "Durendal's Avenger", de: "Durendals Rächer" }, level: 112, min: 415, max: 480, magic: 0 },
    { id: "balmungs_legacy",name: { en: "Balmung's Legacy",   de: "Balmungs Erbe" },       level: 115, min: 432, max: 500, magic: 0 },
  ],
  sword_2h: [
    { id: "spear",            name: { en: "Spear",              de: "Speer" },              level: 10,  min: 22,  max: 32,  magic: 0 },
    { id: "battle_pitchfork", name: { en: "Battle Pitchfork",   de: "Kampfheugabel" },      level: 18,  min: 48,  max: 64,  magic: 0 },
    { id: "partisan",         name: { en: "Partisan",           de: "Partisane" },          level: 25,  min: 72,  max: 92,  magic: 0 },
    { id: "gisarme",          name: { en: "Gisarme",            de: "Guisarme" },           level: 32,  min: 100, max: 125, magic: 0 },
    { id: "halberd",          name: { en: "Halberd",            de: "Hellebarde" },         level: 40,  min: 132, max: 162, magic: 0 },
    { id: "giant_axe",        name: { en: "Giant Axe",          de: "Riesenaxt" },          level: 45,  min: 150, max: 182, magic: 0 },
    { id: "glaive",           name: { en: "Glaive",             de: "Glefe" },              level: 50,  min: 170, max: 205, magic: 0 },
    { id: "orc_butcher",      name: { en: "Orc Butcher",        de: "Orkschlächter" },      level: 55,  min: 190, max: 228, magic: 0 },
    { id: "lion_slayer",      name: { en: "Lion Slayer",        de: "Löwentöter" },         level: 60,  min: 210, max: 250, magic: 0 },
    { id: "spider_spear",     name: { en: "Spider Spear",       de: "Spinnenspeer" },       level: 65,  min: 230, max: 272, magic: 0 },
    { id: "glacial_pick",     name: { en: "Glacial Pick",       de: "Gletscherpicke" },     level: 70,  min: 250, max: 295, magic: 0 },
    { id: "serpent_greatsword", name: { en: "Serpent Greatsword", de: "Schlangengroßschwert" }, level: 75, min: 268, max: 315, magic: 0 },
    { id: "red_iron_blade",   name: { en: "Red Iron Blade",     de: "Roteisenklinge" },     level: 78,  min: 282, max: 330, magic: 0 },
    { id: "zodiac_glaive",    name: { en: "Zodiac Glaive",      de: "Tierkreisglefe" },     level: 80,  min: 295, max: 345, magic: 0 },
    { id: "kyanite_blade",    name: { en: "Kyanite Blade",      de: "Kyanitklinge" },       level: 82,  min: 305, max: 358, magic: 0 },
    { id: "grudge_sword",     name: { en: "Grudge Sword",       de: "Grollschwert" },       level: 85,  min: 318, max: 372, magic: 0 },
    { id: "obsidian_hammer",  name: { en: "Obsidian Hammer",    de: "Obsidianhammer" },     level: 88,  min: 332, max: 388, magic: 0 },
    { id: "gloom_dragon_blade", name: { en: "Gloom Dragon Blade", de: "Dunkeldrachenklinge" }, level: 90, min: 345, max: 402, magic: 0 },
    { id: "soul_stealing_blade", name: { en: "Soul Stealing Blade (2H)", de: "Seelenschlitzer" }, level: 92, min: 358, max: 418, magic: 0 },
    { id: "guillotine_blade", name: { en: "Guillotine Blade",   de: "Enthauptungsklinge" }, level: 94,  min: 370, max: 432, magic: 0 },
    { id: "war_scythe",       name: { en: "War Scythe",         de: "Kriegssense" },        level: 95,  min: 378, max: 440, magic: 0 },
    { id: "electromagnetic",  name: { en: "Electromagnetic Blade", de: "Magnetische Klinge" }, level: 97, min: 390, max: 452, magic: 0 },
    { id: "solar_blade",      name: { en: "Solar Blade",        de: "Sonnenklinge" },       level: 98,  min: 398, max: 462, magic: 0 },
    { id: "thunder_roar",     name: { en: "Thunder Roar",       de: "Donnerhall" },         level: 100, min: 412, max: 478, magic: 0 },
    { id: "twelve_spirit",    name: { en: "Twelve Spirit Sword",de: "Schwert der zwölf Geister" }, level: 102, min: 425, max: 492, magic: 0 },
    { id: "salvation_blade",  name: { en: "Salvation Blade",    de: "Erlösungsklinge" },    level: 104, min: 438, max: 508, magic: 0 },
    { id: "judgment",         name: { en: "The Judgment",       de: "Das Urteil" },         level: 105, min: 448, max: 520, magic: 0 },
    { id: "blood_pact",       name: { en: "Blood Pact",         de: "Blutpakt" },           level: 108, min: 465, max: 540, magic: 0 },
    { id: "brachindul",       name: { en: "Brachindul",         de: "Brachindul" },         level: 110, min: 480, max: 558, magic: 0 },
    { id: "twilight_of_gods", name: { en: "Twilight of the Gods", de: "Götterdämmerung" }, level: 112, min: 495, max: 575, magic: 0 },
    { id: "armageddon",       name: { en: "Armageddon",         de: "Armageddon" },         level: 115, min: 515, max: 595, magic: 0 },
  ],
  dagger: [
    { id: "dagger",          name: { en: "Dagger",            de: "Dolch" },              level: 1,   min: 4,   max: 6,   magic: 0 },
    { id: "short_knife",     name: { en: "Short Knife",       de: "Kurzes Messer" },      level: 6,   min: 11,  max: 15,  magic: 0 },
    { id: "siamese_knife",   name: { en: "Siamese Knife",     de: "Siamesenmesser" },     level: 12,  min: 20,  max: 28,  magic: 0 },
    { id: "lucky_knife",     name: { en: "Lucky Knife",       de: "Glücksmesser" },       level: 18,  min: 32,  max: 42,  magic: 0 },
    { id: "chakram",         name: { en: "Chakram",           de: "Chakram" },            level: 22,  min: 42,  max: 54,  magic: 0 },
    { id: "cobra_dagger",    name: { en: "Cobra Dagger",      de: "Kobradolch" },         level: 28,  min: 56,  max: 72,  magic: 0 },
    { id: "moonlight_scalpel",name:{ en: "Moonlight Scalpel", de: "Mondlichtskalpell" },  level: 32,  min: 68,  max: 86,  magic: 0 },
    { id: "wind_pike",       name: { en: "Wind Pike",         de: "Windstich" },          level: 36,  min: 80,  max: 100, magic: 0 },
    { id: "amija",           name: { en: "Amija",             de: "Amija" },              level: 40,  min: 94,  max: 115, magic: 0 },
    { id: "dragon_knife",    name: { en: "Dragon Knife",      de: "Drachenmesser" },      level: 44,  min: 108, max: 130, magic: 0 },
    { id: "assassin_toothpick", name:{ en: "Assassin Toothpick", de: "Meuchelnder Zahnstocher" }, level: 48, min: 120, max: 145, magic: 0 },
    { id: "cat_bite_knife",  name: { en: "Cat Bite Knife",    de: "Katzenbissmesser" },   level: 52,  min: 134, max: 160, magic: 0 },
    { id: "furious_thorn",   name: { en: "Furious Thorn",     de: "Dornenwut" },          level: 56,  min: 146, max: 175, magic: 0 },
    { id: "rib_knife",       name: { en: "Rib Knife",         de: "Rippenmesser" },       level: 60,  min: 160, max: 190, magic: 0 },
    { id: "elf_capture",     name: { en: "Elf Capture",       de: "Elfenfang" },          level: 64,  min: 172, max: 205, magic: 0 },
    { id: "lightning_knife", name: { en: "Lightning Knife",   de: "Blitzmesser" },        level: 68,  min: 185, max: 220, magic: 0 },
    { id: "bloody_dagger",   name: { en: "Bloody Dagger",     de: "Blutiger Dolch" },     level: 72,  min: 198, max: 235, magic: 0 },
    { id: "serpent_dagger",  name: { en: "Serpent Dagger",    de: "Schlangendolch" },     level: 75,  min: 208, max: 246, magic: 0 },
    { id: "zodiac_dagger",   name: { en: "Zodiac Dagger",     de: "Tierkreisdolch" },     level: 80,  min: 222, max: 262, magic: 0 },
    { id: "kyanite_dagger",  name: { en: "Kyanite Dagger",    de: "Kyanitdolch" },        level: 82,  min: 232, max: 274, magic: 0 },
    { id: "black_leaf_dirk", name: { en: "Black Leaf Dirk",   de: "Schwarzblattdolch" },  level: 85,  min: 244, max: 288, magic: 0 },
    { id: "devil_mask",      name: { en: "Devil Mask Dagger", de: "Dolch Teufelsmaske" }, level: 88,  min: 256, max: 302, magic: 0 },
    { id: "gloom_dragon_dagger", name:{ en:"Gloom Dragon Dagger", de:"Dunkeldrachendolch" }, level:90, min: 268, max: 315, magic: 0 },
    { id: "devil_fist",      name: { en: "Devil Fist Dagger", de: "Dolch der Teufelsfaust" }, level: 92, min: 278, max: 327, magic: 0 },
    { id: "soulless_knife",  name: { en: "Soulless Knife",    de: "Seelenloses Messer" }, level: 94,  min: 288, max: 338, magic: 0 },
    { id: "psychic_slicer",  name: { en: "Psychic Slicer",    de: "Seelenschnitzer" },    level: 96,  min: 298, max: 350, magic: 0 },
    { id: "scissor_dagger",  name: { en: "Scissor Dagger",    de: "Scherendolch" },       level: 98,  min: 308, max: 362, magic: 0 },
    { id: "devil_wing_chakram", name:{ en: "Devil Wing Chakram", de: "Teufelsflügel-Chakram" }, level: 100, min: 320, max: 375, magic: 0 },
    { id: "five_element",    name: { en: "Five Element Blade",de: "Fünf-Elemente-Klinge" }, level: 102, min: 332, max: 388, magic: 0 },
    { id: "death_fairy",     name: { en: "Death Fairy",       de: "Todesfee" },           level: 105, min: 348, max: 405, magic: 0 },
    { id: "nine_blades",     name: { en: "Nine Blades",       de: "Neunklingen" },        level: 108, min: 362, max: 420, magic: 0 },
    { id: "king_slayer",     name: { en: "King Slayer",       de: "Königsmörder" },       level: 112, min: 380, max: 440, magic: 0 },
  ],
  bow: [
    { id: "short_bow",       name: { en: "Short Bow",         de: "Kurzbogen" },          level: 1,   min: 4,   max: 6,   magic: 0 },
    { id: "long_bow",        name: { en: "Long Bow",          de: "Langbogen" },          level: 8,   min: 14,  max: 20,  magic: 0 },
    { id: "composite_bow",   name: { en: "Composite Bow",     de: "Kompositbogen" },      level: 15,  min: 28,  max: 38,  magic: 0 },
    { id: "hornbow",         name: { en: "Hornbow",           de: "Hornbogen" },          level: 22,  min: 44,  max: 58,  magic: 0 },
    { id: "copper_bow",      name: { en: "Copper Crafted Bow",de: "Kupferverzierter Bogen" }, level: 28, min: 58, max: 75, magic: 0 },
    { id: "bull_horn_bow",   name: { en: "Bull's Horn Bow",   de: "Bullenhornbogen" },    level: 34,  min: 74,  max: 92,  magic: 0 },
    { id: "battle_bow",      name: { en: "Battle Bow",        de: "Kriegsbogen" },        level: 40,  min: 90,  max: 110, magic: 0 },
    { id: "horseback_long",  name: { en: "Horseback Long Bow",de: "Reiterlangbogen" },    level: 45,  min: 105, max: 128, magic: 0 },
    { id: "horseback_battle",name: { en: "Horseback Battle Bow", de: "Reiterkriegsbogen" }, level: 48, min: 115, max: 138, magic: 0 },
    { id: "unicorn_bow",     name: { en: "Unicorn Bow",       de: "Einhornbogen" },       level: 52,  min: 128, max: 152, magic: 0 },
    { id: "thorn_leaf_bow",  name: { en: "Thorn Leaf Bow",    de: "Dornblattbogen" },     level: 56,  min: 140, max: 168, magic: 0 },
    { id: "phoenix_bow",     name: { en: "Phoenix Bow",       de: "Phönixbogen" },        level: 60,  min: 154, max: 184, magic: 0 },
    { id: "red_eye_bow",     name: { en: "Red Eye Bow",       de: "Rotaugenbogen" },      level: 64,  min: 168, max: 198, magic: 0 },
    { id: "giant_devil_bow", name: { en: "Giant Devil Bow",   de: "Großteufelbogen" },    level: 68,  min: 180, max: 212, magic: 0 },
    { id: "crow_steel_bow",  name: { en: "Crow Steel Bow",    de: "Krähenstahlbogen" },   level: 72,  min: 194, max: 228, magic: 0 },
    { id: "serpent_bow",     name: { en: "Serpent Bow",       de: "Schlangenbogen" },     level: 75,  min: 204, max: 240, magic: 0 },
    { id: "zodiac_bow",      name: { en: "Zodiac Bow",        de: "Tierkreisbogen" },     level: 80,  min: 220, max: 258, magic: 0 },
    { id: "kyanite_bow",     name: { en: "Kyanite Bow",       de: "Kyanitbogen" },        level: 82,  min: 230, max: 270, magic: 0 },
    { id: "yellow_dragon",   name: { en: "Yellow Dragon Bow", de: "Großgelbdrachenbogen" }, level: 85, min: 242, max: 285, magic: 0 },
    { id: "giant_wing",      name: { en: "Giant Wing Bow",    de: "Riesenflügelbogen" },  level: 88,  min: 254, max: 298, magic: 0 },
    { id: "blue_dragon",     name: { en: "Blue Dragon Bow",   de: "Blaudrachenbogen" },   level: 90,  min: 266, max: 312, magic: 0 },
    { id: "gloom_dragon_bow",name: { en: "Gloom Dragon Bow",  de: "Dunkeldrachenbogen" }, level: 92,  min: 276, max: 324, magic: 0 },
    { id: "black_ruin_bow",  name: { en: "Black Ruin Bow",    de: "Schwarzruinenbogen" }, level: 95,  min: 290, max: 340, magic: 0 },
    { id: "divine_apricot",  name: { en: "Divine Apricot Bow",de: "Aprikosen-Bogen" },    level: 98,  min: 302, max: 354, magic: 0 },
    { id: "shadow_leaf",     name: { en: "Shadow Leaf",       de: "Schattenblatt" },      level: 100, min: 315, max: 368, magic: 0 },
    { id: "lament",          name: { en: "Lament",            de: "Klagelied" },          level: 102, min: 325, max: 380, magic: 0 },
    { id: "dream_catcher",   name: { en: "Dream Catcher",     de: "Traumfänger" },        level: 105, min: 340, max: 397, magic: 0 },
    { id: "storm_messenger", name: { en: "Storm Messenger",   de: "Sturmbote" },          level: 108, min: 355, max: 412, magic: 0 },
    { id: "ependrion",       name: { en: "Ependrion",         de: "Ependrion" },          level: 110, min: 368, max: 428, magic: 0 },
    { id: "voice_of_titans", name: { en: "Voice of Titans",   de: "Stimme der Titanen" }, level: 112, min: 382, max: 442, magic: 0 },
    { id: "tendon_of_gods",  name: { en: "Tendon of the Gods",de: "Göttersehne" },        level: 114, min: 395, max: 458, magic: 0 },
    { id: "dragon_breath",   name: { en: "Dragon Breath",     de: "Drachenhauch" },       level: 115, min: 405, max: 470, magic: 0 },
  ],
  bell: [
    { id: "bamboo_bell",     name: { en: "Bamboo Bell",       de: "Bambusglocke" },       level: 5,   min: 6,   max: 10,  magic: 12 },
    { id: "copper_bell",     name: { en: "Copper Bell",       de: "Kupferglocke" },       level: 12,  min: 14,  max: 20,  magic: 26 },
    { id: "silver_bell",     name: { en: "Silver Bell",       de: "Silberglocke" },       level: 20,  min: 25,  max: 35,  magic: 45 },
    { id: "golden_bell",     name: { en: "Golden Bell",       de: "Goldglocke" },         level: 28,  min: 38,  max: 52,  magic: 68 },
    { id: "jade_bell",       name: { en: "Jade Bell",         de: "Jadeglocke" },         level: 35,  min: 52,  max: 68,  magic: 90 },
    { id: "fountain_bell",   name: { en: "Fountain Bell",     de: "Brunnenglocke" },      level: 42,  min: 66,  max: 86,  magic: 115 },
    { id: "apricot_bell",    name: { en: "Apricot Bell",      de: "Aprikosenglocke" },    level: 48,  min: 80,  max: 102, magic: 138 },
    { id: "antique_bell",    name: { en: "Antique Bell",      de: "Antike Glocke" },      level: 54,  min: 95,  max: 120, magic: 162 },
    { id: "steel_bug_bell",  name: { en: "Steel Bug Bell",    de: "Stahlkäferglocke" },   level: 60,  min: 110, max: 138, magic: 188 },
    { id: "golden_bug_bell", name: { en: "Golden Bug Bell",   de: "Goldkäferglocke" },    level: 65,  min: 122, max: 152, magic: 208 },
    { id: "heaven_earth",    name: { en: "Heaven and Earth Bell", de: "Himmel-&-Erde-Glocke" }, level: 70, min: 135, max: 168, magic: 230 },
    { id: "magical_bell",    name: { en: "Magical Bell",      de: "Magische Glocke" },    level: 74,  min: 145, max: 180, magic: 248 },
    { id: "serpent_bell",    name: { en: "Serpent Bell",      de: "Schlangenglocke" },    level: 78,  min: 156, max: 194, magic: 266 },
    { id: "zodiac_bell",     name: { en: "Zodiac Bell",       de: "Tierkreisglocke" },    level: 80,  min: 162, max: 202, magic: 278 },
    { id: "kyanite_bell",    name: { en: "Kyanite Bell",      de: "Kyanitglocke" },       level: 82,  min: 168, max: 210, magic: 290 },
    { id: "thunder_bird",    name: { en: "Thunder Bird Bell", de: "Donnervogelglocke" },  level: 85,  min: 178, max: 222, magic: 308 },
    { id: "dragon_jaw_bell", name: { en: "Dragon Jaw Bell",   de: "Drachenmaulglocke" },  level: 88,  min: 188, max: 234, magic: 326 },
    { id: "gloom_dragon_bell", name:{ en:"Gloom Dragon Bell", de: "Dunkeldrachenglocke" },level: 90,  min: 196, max: 246, magic: 344 },
    { id: "dragon_ghost",    name: { en: "Dragon Ghost Bell", de: "Drachengeist-Glocke" },level: 92,  min: 205, max: 256, magic: 360 },
    { id: "elf_kiss",        name: { en: "Elf Kiss",          de: "Elfenkuss" },          level: 95,  min: 218, max: 272, magic: 384 },
    { id: "death_kiss",      name: { en: "Death Kiss",        de: "Todeskuss" },          level: 98,  min: 230, max: 286, magic: 406 },
    { id: "singing_fury",    name: { en: "Singing Fury",      de: "Singende Furie" },     level: 100, min: 240, max: 298, magic: 422 },
    { id: "honor_chime",     name: { en: "Honor Chime",       de: "Ehrenklang" },         level: 102, min: 250, max: 310, magic: 438 },
    { id: "storm_call",      name: { en: "Storm Call",        de: "Sturmruf" },           level: 105, min: 265, max: 328, magic: 462 },
    { id: "thunder_hall",    name: { en: "Thunder Hall",      de: "Donnerschlag" },       level: 108, min: 278, max: 344, magic: 484 },
    { id: "final_blow",      name: { en: "Final Blow",        de: "Letzter Schlag" },     level: 110, min: 290, max: 358, magic: 504 },
    { id: "valkyrie_call",   name: { en: "Valkyrie's Call",   de: "Walkürenruf" },        level: 115, min: 308, max: 380, magic: 535 },
  ],
  fan: [
    { id: "fan",             name: { en: "Fan",               de: "Fächer" },             level: 5,   min: 6,   max: 10,  magic: 12 },
    { id: "iron_fan",        name: { en: "Iron Fan",          de: "Eisenfächer" },        level: 12,  min: 14,  max: 20,  magic: 26 },
    { id: "crane_wing",      name: { en: "Crane Wing Fan",    de: "Kranichflügelfächer" },level: 20,  min: 25,  max: 35,  magic: 45 },
    { id: "stone_fan",       name: { en: "Stone Fan",         de: "Steinfächer" },        level: 28,  min: 38,  max: 52,  magic: 68 },
    { id: "aquatic_fan",     name: { en: "Aquatic Fan",       de: "Aquatischer Fächer" }, level: 35,  min: 52,  max: 68,  magic: 90 },
    { id: "ocean_fan",       name: { en: "Ocean Fan",         de: "Ozeanfächer" },        level: 42,  min: 66,  max: 86,  magic: 115 },
    { id: "sting_fan",       name: { en: "Sting Fan",         de: "Stichfächer" },        level: 48,  min: 80,  max: 102, magic: 138 },
    { id: "autumn_wind",     name: { en: "Autumn Wind Fan",   de: "Herbstwindfächer" },   level: 54,  min: 95,  max: 120, magic: 162 },
    { id: "triple_fan",      name: { en: "Triple Fan",        de: "Dreifachfächer" },     level: 60,  min: 110, max: 138, magic: 188 },
    { id: "peacock_fan",     name: { en: "Peacock Fan",       de: "Pfauenfächer" },       level: 65,  min: 122, max: 152, magic: 208 },
    { id: "black_tiger",     name: { en: "Black Tiger Fan",   de: "Schwarztigerfächer" }, level: 70,  min: 135, max: 168, magic: 230 },
    { id: "lying_dragon",    name: { en: "Lying Dragon Fan",  de: "Drachenfächer" },      level: 74,  min: 145, max: 180, magic: 248 },
    { id: "demon_fan",       name: { en: "Demon Fan",         de: "Dämonenfächer" },      level: 78,  min: 156, max: 194, magic: 266 },
    { id: "serpent_fan",     name: { en: "Serpent Fan",       de: "Schlangenfächer" },    level: 79,  min: 160, max: 200, magic: 274 },
    { id: "zodiac_fan",      name: { en: "Zodiac Fan",        de: "Tierkreisfächer" },    level: 80,  min: 162, max: 202, magic: 278 },
    { id: "kyanite_fan",     name: { en: "Kyanite Fan",       de: "Kyanitfächer" },       level: 82,  min: 168, max: 210, magic: 290 },
    { id: "ecstasy_fan",     name: { en: "Ecstasy Fan",       de: "Ekstasefächer" },      level: 85,  min: 178, max: 222, magic: 308 },
    { id: "heavenly_bird",   name: { en: "Heavenly Bird Fan", de: "Himmelsvogelfächer" }, level: 88,  min: 188, max: 234, magic: 326 },
    { id: "gloom_dragon_fan",name: { en: "Gloom Dragon Fan",  de: "Dunkeldrachenfächer" },level: 90,  min: 196, max: 246, magic: 344 },
    { id: "phoenix_fan",     name: { en: "Phoenix Fan",       de: "Phönixfächer" },       level: 92,  min: 205, max: 256, magic: 360 },
    { id: "black_sun",       name: { en: "Black Sun Fan",     de: "Schwarzsonnenfächer" },level: 95,  min: 218, max: 272, magic: 384 },
    { id: "wind_sound",      name: { en: "Sound of Wind",     de: "Bruit du vent" },      level: 98,  min: 230, max: 286, magic: 406 },
    { id: "shadow_dancer",   name: { en: "Shadow Dancer",     de: "Schattentänzer" },     level: 100, min: 240, max: 298, magic: 422 },
    { id: "salvation_fan",   name: { en: "Salvation Fan",     de: "Erlösungsfächer" },    level: 102, min: 250, max: 310, magic: 438 },
    { id: "nexus",           name: { en: "Nexus",             de: "Nexus" },              level: 105, min: 265, max: 328, magic: 462 },
    { id: "raven_claw",      name: { en: "Raven Claw",        de: "Rabenklaue" },         level: 108, min: 278, max: 344, magic: 484 },
    { id: "kor_glash",       name: { en: "Kor Glâsh",         de: "Kor-Glâsh" },          level: 110, min: 290, max: 358, magic: 504 },
    { id: "widow_avenger",   name: { en: "Widow's Avenger",   de: "Witwen-Rächer" },      level: 112, min: 302, max: 372, magic: 524 },
    { id: "silent_curse",    name: { en: "Silent Curse",      de: "Stiller Fluch" },      level: 114, min: 312, max: 384, magic: 540 },
    { id: "belial_tessen",   name: { en: "Belial's Tessen",   de: "Belials Tessen" },     level: 115, min: 318, max: 392, magic: 552 },
    { id: "eyebrow_fan",     name: { en: "Eyebrow Fan",       de: "Brauenfächer" },       level: 117, min: 328, max: 405, magic: 570 },
  ],
  lame: [
    { id: "edge_blade",      name: { en: "Edge Blade",        de: "Schnittklinge" },      level: 25,  min: 52,  max: 70,  magic: 0 },
    { id: "lion_sword",      name: { en: "Lion Sword",        de: "Löwenschwert" },       level: 40,  min: 105, max: 132, magic: 0 },
    { id: "exorcism_sword",  name: { en: "Exorcism Sword",    de: "Exorzismusschwert" },  level: 55,  min: 162, max: 198, magic: 0 },
    { id: "serpent_blade",   name: { en: "Serpent Blade",     de: "Schlangenklinge" },    level: 70,  min: 225, max: 268, magic: 0 },
    { id: "demon_blade",     name: { en: "Demon Blade",       de: "Dämonenklinge" },      level: 78,  min: 268, max: 318, magic: 0 },
    { id: "zodiac_blade",    name: { en: "Zodiac Blade",      de: "Tierkreisklinge" },    level: 80,  min: 282, max: 332, magic: 0 },
    { id: "kyanite_sword",   name: { en: "Kyanite Sword",     de: "Kyanitschwert" },      level: 82,  min: 292, max: 345, magic: 0 },
    { id: "dragon_tooth",    name: { en: "Dragon Tooth Blade",de: "Drachenzahnklinge" },  level: 88,  min: 318, max: 374, magic: 0 },
    { id: "gloom_dragon_sabre", name:{ en:"Gloom Dragon Sabre", de:"Dunkeldrachenschneide" }, level: 90, min: 328, max: 388, magic: 0 },
    { id: "ghost_fang",      name: { en: "Ghost Fang Blade",  de: "Geisterzahnklinge" },  level: 95,  min: 352, max: 412, magic: 0 },
    { id: "holy_sword",      name: { en: "Holy Sword",        de: "Heiliges Schwert" },   level: 105, min: 392, max: 458, magic: 0 },
  ],
  claw: [
    { id: "iron_claw",       name: { en: "Iron Claw",         de: "Eisenkralle" },        level: 5,   min: 12,  max: 18,  magic: 0 },
    { id: "steel_claw",      name: { en: "Steel Claw",        de: "Stahlkralle" },        level: 15,  min: 30,  max: 42,  magic: 0 },
    { id: "scarab_claw",     name: { en: "Scarab Claw",       de: "Skarabäuskralle" },    level: 25,  min: 52,  max: 68,  magic: 0 },
    { id: "hawk_claw",       name: { en: "Hawk Claw",         de: "Habichtskralle" },     level: 35,  min: 78,  max: 98,  magic: 0 },
    { id: "serpent_claw",    name: { en: "Serpent Claw",      de: "Schlangenkralle" },    level: 45,  min: 108, max: 132, magic: 0 },
    { id: "thorned_claw",    name: { en: "Thorned Claw",      de: "Dornenkralle" },       level: 52,  min: 130, max: 158, magic: 0 },
    { id: "green_wolf_fang", name: { en: "Green Wolf Fang",   de: "Grüner Wolfsfang" },   level: 60,  min: 158, max: 188, magic: 0 },
    { id: "velvet_paws",     name: { en: "Velvet Paws",       de: "Samtpfoten" },         level: 65,  min: 175, max: 208, magic: 0 },
    { id: "predator_claw",   name: { en: "Predator Claw",     de: "Raubtierkralle" },     level: 70,  min: 195, max: 230, magic: 0 },
    { id: "torment_claws",   name: { en: "Claws of Torment",  de: "Klauen der Pein" },    level: 75,  min: 215, max: 252, magic: 0 },
    { id: "zodiac_claw",     name: { en: "Zodiac Claw",       de: "Tierkreiskralle" },    level: 80,  min: 235, max: 275, magic: 0 },
    { id: "kyanite_claw",    name: { en: "Kyanite Claw",      de: "Kyanitkralle" },       level: 82,  min: 245, max: 287, magic: 0 },
    { id: "blind_fury",      name: { en: "Blind Fury",        de: "Blinde Wut" },         level: 85,  min: 258, max: 302, magic: 0 },
    { id: "raptors",         name: { en: "Raptors",           de: "Raptoren" },           level: 88,  min: 270, max: 316, magic: 0 },
    { id: "gloom_dragon_claw", name:{ en:"Gloom Dragon Claws",de: "Dunkeldrachenkralle" },level: 90,  min: 282, max: 330, magic: 0 },
    { id: "phoenix_lance",   name: { en: "Phoenix Lance",     de: "Phönixspieß" },        level: 92,  min: 292, max: 342, magic: 0 },
    { id: "dissector",       name: { en: "Dissector",         de: "Sezierer" },           level: 95,  min: 308, max: 360, magic: 0 },
    { id: "psychic_ripper",  name: { en: "Psychic Ripper",    de: "Psycho-Reißer" },      level: 98,  min: 320, max: 374, magic: 0 },
    { id: "destiny_claws",   name: { en: "Claws of Destiny",  de: "Schicksalsklauen" },   level: 100, min: 332, max: 388, magic: 0 },
    { id: "steel_torch",     name: { en: "Steel Torch",       de: "Stahlfackel" },        level: 102, min: 342, max: 400, magic: 0 },
    { id: "thunder_lightning",name:{ en: "Lightning & Thunder",de: "Blitz & Donner" },    level: 105, min: 358, max: 418, magic: 0 },
    { id: "dragon_lord",     name: { en: "Dragon Lord",       de: "Drachenherrscher" },   level: 110, min: 380, max: 442, magic: 0 },
  ],
};

const RACES = ["human", "animal", "orc", "mystic", "undead", "devil"];
const ELEMENTS = ["fire", "ice", "lightning", "wind", "earth", "dark"];

// Mobs / bosses / metin stones. EN names from en-wiki, DE from de-wiki.
const MOBS = [
  { id: "wild_dog",         name: { en: "Wild Dog",          de: "Wildhund" },           kind: "monster", race: "animal", level: 1,   hp: 100,     def: 5,    mdef: 2   },
  { id: "stray_dog",        name: { en: "Stray Dog",         de: "Streunender Hund" },   kind: "monster", race: "animal", level: 3,   hp: 180,     def: 8,    mdef: 3   },
  { id: "wolf_cub",         name: { en: "Wolf Cub",          de: "Wolfsjunges" },        kind: "monster", race: "animal", level: 5,   hp: 280,     def: 12,   mdef: 5   },
  { id: "wild_boar",        name: { en: "Wild Boar",         de: "Wildschwein" },        kind: "monster", race: "animal", level: 8,   hp: 600,     def: 18,   mdef: 8   },
  { id: "grey_wolf",        name: { en: "Grey Wolf",         de: "Grauer Wolf" },        kind: "monster", race: "animal", level: 12,  hp: 1100,    def: 28,   mdef: 12  },
  { id: "black_wolf",       name: { en: "Black Wolf",        de: "Schwarzer Wolf" },     kind: "monster", race: "animal", level: 17,  hp: 1900,    def: 40,   mdef: 18  },
  { id: "wolf_chief",       name: { en: "Wolf Chief",        de: "Wolfshäuptling" },     kind: "boss",    race: "animal", level: 18,  hp: 60000,   def: 80,   mdef: 40  },
  { id: "bandit",           name: { en: "Bandit",            de: "Bandit" },             kind: "monster", race: "human",  level: 10,  hp: 800,     def: 22,   mdef: 10  },
  { id: "bandit_archer",    name: { en: "Bandit Archer",     de: "Banditen-Bogenschütze" },kind: "monster", race: "human",level: 14,  hp: 1300,    def: 30,   mdef: 14  },
  { id: "bandit_leader",    name: { en: "Bandit Leader",     de: "Banditenanführer" },   kind: "boss",    race: "human",  level: 20,  hp: 80000,   def: 95,   mdef: 50  },
  { id: "orc",              name: { en: "Orc",               de: "Ork" },                kind: "monster", race: "orc",    level: 18,  hp: 2200,    def: 45,   mdef: 20  },
  { id: "orc_warrior",      name: { en: "Orc Warrior",       de: "Ork-Krieger" },        kind: "monster", race: "orc",    level: 22,  hp: 3400,    def: 60,   mdef: 28  },
  { id: "orc_archer",       name: { en: "Orc Archer",        de: "Ork-Bogenschütze" },   kind: "monster", race: "orc",    level: 25,  hp: 4500,    def: 70,   mdef: 32  },
  { id: "orc_warlord",      name: { en: "Orc Warlord",       de: "Ork-Heerführer" },     kind: "monster", race: "orc",    level: 28,  hp: 6500,    def: 90,   mdef: 45  },
  { id: "orc_lord",         name: { en: "Orc Lord",          de: "Orklord" },            kind: "boss",    race: "orc",    level: 30,  hp: 180000,  def: 140,  mdef: 80  },
  { id: "dark_ghost",       name: { en: "Dark Ghost",        de: "Dunkler Geist" },      kind: "monster", race: "undead", level: 24,  hp: 4000,    def: 70,   mdef: 50  },
  { id: "esoteric_seeker",  name: { en: "Esoteric Seeker",   de: "Esoterischer Sucher" },kind: "monster", race: "mystic", level: 30,  hp: 7500,    def: 110,  mdef: 80  },
  { id: "esoteric_assassin",name: { en: "Esoteric Assassin", de: "Esoterischer Assassine" },kind: "monster",race: "mystic",level:34,  hp: 10500,   def: 140,  mdef: 95  },
  { id: "esoteric_pikeman", name: { en: "Esoteric Pikeman",  de: "Esoterischer Lanzenträger" }, kind: "monster", race: "mystic", level: 36, hp: 12500, def: 160, mdef: 105 },
  { id: "esoteric_warlord", name: { en: "Esoteric Warlord",  de: "Esoterischer Heerführer" }, kind: "boss", race: "mystic", level: 40, hp: 250000, def: 230, mdef: 160 },
  { id: "scarecrow",        name: { en: "Scarecrow",         de: "Vogelscheuche" },      kind: "monster", race: "undead", level: 32,  hp: 9000,    def: 130,  mdef: 90  },
  { id: "ghost_warrior",    name: { en: "Ghost Warrior",     de: "Geisterkrieger" },     kind: "monster", race: "undead", level: 38,  hp: 15000,   def: 180,  mdef: 130 },
  { id: "razor_claw",       name: { en: "Razor Claw",        de: "Klingenkralle" },      kind: "monster", race: "animal", level: 42,  hp: 18500,   def: 210,  mdef: 130 },
  { id: "desert_bandit",    name: { en: "Desert Bandit",     de: "Wüstenbandit" },       kind: "monster", race: "human",  level: 44,  hp: 21000,   def: 230,  mdef: 150 },
  { id: "salamander",       name: { en: "Salamander",        de: "Salamander" },         kind: "monster", race: "mystic", level: 46,  hp: 24000,   def: 250,  mdef: 170 },
  { id: "snake_lady",       name: { en: "Snake Lady",        de: "Schlangendame" },      kind: "boss",    race: "mystic", level: 50,  hp: 420000,  def: 320,  mdef: 240 },
  { id: "death_reaper",     name: { en: "Death Reaper",      de: "Todessenser" },        kind: "monster", race: "undead", level: 48,  hp: 28000,   def: 290,  mdef: 200 },
  { id: "demon_spider",     name: { en: "Demon Spider",      de: "Dämonenspinne" },      kind: "monster", race: "mystic", level: 52,  hp: 35000,   def: 320,  mdef: 220 },
  { id: "spider_baby",      name: { en: "Spider Baby",       de: "Spinnenbaby" },        kind: "monster", race: "mystic", level: 50,  hp: 30000,   def: 290,  mdef: 200 },
  { id: "spider_arrow",     name: { en: "Spider Arrow",      de: "Pfeilspinne" },        kind: "monster", race: "mystic", level: 55,  hp: 42000,   def: 340,  mdef: 240 },
  { id: "spider_queen",     name: { en: "Spider Queen",      de: "Spinnenkönigin" },     kind: "boss",    race: "mystic", level: 60,  hp: 1500000, def: 480,  mdef: 360 },
  { id: "tower_zombie",     name: { en: "Tower Zombie",      de: "Turm-Zombie" },        kind: "monster", race: "undead", level: 55,  hp: 45000,   def: 360,  mdef: 260 },
  { id: "tower_phantom",    name: { en: "Tower Phantom",     de: "Turm-Phantom" },       kind: "monster", race: "undead", level: 60,  hp: 60000,   def: 410,  mdef: 300 },
  { id: "tower_demon",      name: { en: "Tower Demon",       de: "Turm-Dämon" },         kind: "monster", race: "devil",  level: 65,  hp: 80000,   def: 470,  mdef: 340 },
  { id: "tartaros",         name: { en: "Demon King Tartaros", de: "Dämonenkönig Tartaros" }, kind: "boss", race: "devil", level: 70, hp: 3500000, def: 700, mdef: 520 },
  { id: "ice_witch",        name: { en: "Ice Witch",         de: "Eis-Hexe" },           kind: "monster", race: "mystic", level: 70,  hp: 95000,   def: 530,  mdef: 420 },
  { id: "ice_golem",        name: { en: "Ice Golem",         de: "Eis-Golem" },          kind: "monster", race: "mystic", level: 75,  hp: 130000,  def: 620,  mdef: 450 },
  { id: "frost_giant",      name: { en: "Frost Giant",       de: "Frostriese" },         kind: "monster", race: "mystic", level: 78,  hp: 160000,  def: 680,  mdef: 470 },
  { id: "snow_witch",       name: { en: "Snow Witch",        de: "Schneehexe" },         kind: "boss",    race: "mystic", level: 80,  hp: 4500000, def: 820,  mdef: 640 },
  { id: "nemere",           name: { en: "Nemere",            de: "Nemere" },             kind: "boss",    race: "devil",  level: 95,  hp: 7000000, def: 1050, mdef: 820 },
  { id: "skeleton_soldier", name: { en: "Skeleton Soldier",  de: "Skelett-Soldat" },     kind: "monster", race: "undead", level: 80,  hp: 180000,  def: 720,  mdef: 500 },
  { id: "skeleton_warrior", name: { en: "Skeleton Warrior",  de: "Skelett-Krieger" },    kind: "monster", race: "undead", level: 84,  hp: 220000,  def: 780,  mdef: 540 },
  { id: "skeleton_lord",    name: { en: "Skeleton Lord",     de: "Skelett-Lord" },       kind: "monster", race: "undead", level: 88,  hp: 270000,  def: 850,  mdef: 590 },
  { id: "death_horse",      name: { en: "Death Horse",       de: "Todespferd" },         kind: "monster", race: "undead", level: 90,  hp: 310000,  def: 900,  mdef: 620 },
  { id: "death_rider",      name: { en: "Death Rider",       de: "Todesreiter" },        kind: "boss",    race: "undead", level: 95,  hp: 6000000, def: 1000, mdef: 780 },
  { id: "fire_imp",         name: { en: "Fire Imp",          de: "Feuerkobold" },        kind: "monster", race: "devil",  level: 95,  hp: 350000,  def: 950,  mdef: 700 },
  { id: "lava_minion",      name: { en: "Lava Minion",       de: "Lava-Diener" },        kind: "monster", race: "devil",  level: 100, hp: 450000,  def: 1050, mdef: 780 },
  { id: "razador",          name: { en: "Razador",           de: "Razador" },            kind: "boss",    race: "devil",  level: 105, hp: 9000000, def: 1300, mdef: 980 },
  { id: "beran_setaou",     name: { en: "Beran-Setaou",      de: "Beran-Setaou" },       kind: "boss",    race: "devil",  level: 105, hp: 9500000, def: 1320, mdef: 1000 },
  { id: "bairog",           name: { en: "Bairog",            de: "Bairog" },             kind: "boss",    race: "devil",  level: 110, hp: 12000000,def: 1450, mdef: 1100 },
  { id: "aqua_dragon",      name: { en: "Aqua Dragon",       de: "Aqua-Drache" },        kind: "boss",    race: "mystic", level: 110, hp: 12000000,def: 1400, mdef: 1200 },
  { id: "meley",            name: { en: "Meley",             de: "Meley" },              kind: "boss",    race: "devil",  level: 115, hp: 18000000,def: 1600, mdef: 1300 },

  // Metin stones
  { id: "stone_quietude",   name: { en: "Metin of Quietude", de: "Metin der Stille" },          kind: "metin", race: "none", level: 12,  hp: 2400,   def: 35,  mdef: 25  },
  { id: "stone_bravery",    name: { en: "Metin of Bravery",  de: "Metin des Mutes" },           kind: "metin", race: "none", level: 18,  hp: 4500,   def: 60,  mdef: 40  },
  { id: "stone_restraint",  name: { en: "Metin of Restraint",de: "Metin der Zurückhaltung" },   kind: "metin", race: "none", level: 24,  hp: 7000,   def: 90,  mdef: 60  },
  { id: "stone_soul",       name: { en: "Metin of Soul",     de: "Metin der Seele" },           kind: "metin", race: "none", level: 30,  hp: 11000,  def: 130, mdef: 90  },
  { id: "stone_pain",       name: { en: "Metin of Pain",     de: "Metin des Schmerzes" },       kind: "metin", race: "none", level: 36,  hp: 16000,  def: 170, mdef: 120 },
  { id: "stone_chaos",      name: { en: "Metin of Chaos",    de: "Metin des Chaos" },           kind: "metin", race: "none", level: 42,  hp: 24000,  def: 220, mdef: 160 },
  { id: "stone_death",      name: { en: "Metin of Death",    de: "Metin des Todes" },           kind: "metin", race: "none", level: 48,  hp: 34000,  def: 280, mdef: 200 },
  { id: "stone_greed",      name: { en: "Metin of Greed",    de: "Metin der Gier" },            kind: "metin", race: "none", level: 55,  hp: 50000,  def: 350, mdef: 250 },
  { id: "stone_madness",    name: { en: "Metin of Madness",  de: "Metin des Wahnsinns" },       kind: "metin", race: "none", level: 62,  hp: 72000,  def: 430, mdef: 310 },
  { id: "stone_crime",      name: { en: "Metin of Crime",    de: "Metin des Verbrechens" },     kind: "metin", race: "none", level: 70,  hp: 105000, def: 530, mdef: 380 },
  { id: "stone_murder",     name: { en: "Metin of Murder",   de: "Metin des Mordes" },          kind: "metin", race: "none", level: 78,  hp: 150000, def: 640, mdef: 460 },
  { id: "stone_possession", name: { en: "Metin of Possession",de:"Metin der Besessenheit" },    kind: "metin", race: "none", level: 86,  hp: 215000, def: 760, mdef: 550 },
  { id: "stone_curse",      name: { en: "Metin of Curse",    de: "Metin des Fluchs" },          kind: "metin", race: "none", level: 95,  hp: 320000, def: 900, mdef: 660 },
  { id: "stone_oblivion",   name: { en: "Metin of Oblivion", de: "Metin des Vergessens" },      kind: "metin", race: "none", level: 100, hp: 450000, def: 1050,mdef: 780 },
  { id: "stone_devil",      name: { en: "Metin of the Devil",de: "Metin des Teufels" },         kind: "metin", race: "none", level: 105, hp: 600000, def: 1200,mdef: 900 },
];

// Full 1:1 field catalogue mirroring the wiki simulator.
// Sections + exact labels used by the original tool.
const FIELDS = {
  identity: [
    { k: "name",  label: { en: "Name",  de: "Name"        }, type: "text"  },
    { k: "cls",   label: { en: "Class", de: "Klasse"      }, type: "class" },
    { k: "level", label: { en: "Level", de: "Stufe"       }, type: "number" },
    { k: "str",   label: { en: "STR",   de: "STR"         }, type: "number" },
    { k: "dex",   label: { en: "DEX",   de: "GES"         }, type: "number" },
    { k: "vit",   label: { en: "VIT",   de: "VIT"         }, type: "number" },
    { k: "int",   label: { en: "INT",   de: "INT"         }, type: "number" },
    { k: "hp",    label: { en: "HP",    de: "TP"          }, type: "number" },
  ],
  weapon: [
    { k: "wpnType",   label: { en: "Weapon type",        de: "Waffentyp"          }, type: "weaponType" },
    { k: "wpnPreset", label: { en: "Weapon (preset)",    de: "Waffe (Vorlage)"    }, type: "weaponPreset" },
    { k: "wpnMin",    label: { en: "Min ATK",            de: "Min Angriff"        }, type: "number" },
    { k: "wpnMax",    label: { en: "Max ATK",            de: "Max Angriff"        }, type: "number" },
    { k: "wpnMagic",  label: { en: "Magic ATK",          de: "Magischer Angriff"  }, type: "number" },
    { k: "wpnRefine", label: { en: "Refine (+0 to +9)",  de: "Aufwertung (+0 bis +9)" }, type: "number" },
  ],

  damageDefense: [
    { k: "strongMetin",      label: { en: "Strong against Metin Stones",    de: "Stark gegen Metinsteine" } },
    { k: "strongHalfHumans", label: { en: "Strong against Half Humans",     de: "Stark gegen Halbmenschen" } },
    { k: "resHalfHumans",    label: { en: "Resistance against Half Humans", de: "Widerstand gegen Halbmenschen" } },
    { k: "strongOrcs",       label: { en: "Strong against Orcs",            de: "Stark gegen Orks" } },
    { k: "strongUndead",     label: { en: "Strong against Undead",          de: "Stark gegen Untote" } },
    { k: "strongMonsters",   label: { en: "Strength against Monsters",      de: "Stark gegen Monster" } },
    { k: "strongZodiac",     label: { en: "Strong against Zodiac Monsters", de: "Stark gegen Tierkreismonster" } },
    { k: "resMonsters",      label: { en: "Resistance against Monsters",    de: "Widerstand gegen Monster" } },
    { k: "strongAnimals",    label: { en: "Strong against Animals",         de: "Stark gegen Tiere" } },
    { k: "strongMystics",    label: { en: "Strong against Mystics",         de: "Stark gegen Esoterische" } },
    { k: "strongDevils",     label: { en: "Strong against Devil",           de: "Stark gegen Teufel" } },
    { k: "strongDesert",     label: { en: "Strong against Desert Monsters", de: "Stark gegen Wüstenmonster" } },
    { k: "strongInsects",    label: { en: "Strong against Insects",         de: "Stark gegen Insekten" } },
    { k: "strongDragons",    label: { en: "Strong against Dragons",         de: "Stark gegen Drachen" } },
    { k: "atkValuePct",      label: { en: "Attack Value (%)",               de: "Angriffswert (%)" } },
    { k: "atkValueFlat",     label: { en: "Attack Value",                   de: "Angriffswert" } },
    { k: "defValuePct",      label: { en: "Defence (%)",                    de: "Verteidigung (%)" } },
    { k: "defValueFlat",     label: { en: "Defence Value",                  de: "Verteidigungswert" } },
    { k: "avgDamage",        label: { en: "Average Damage",                 de: "Durchschnittlicher Schaden" } },
    { k: "resAvgDamage",     label: { en: "Average Damage Resistance",      de: "Widerstand gegen durchschn. Schaden" } },
    { k: "skillDamage",      label: { en: "Skill Damage",                   de: "Fertigkeitsschaden" } },
    { k: "resSkillDamage",   label: { en: "Skill Damage Resistance",        de: "Widerstand gegen Fertigkeitsschaden" } },
    { k: "meleeMagicAtk",    label: { en: "Melee/Magic Attack",             de: "Nah-/Magieangriff" } },
    { k: "magicAtk",         label: { en: "Magic Attack",                   de: "Magischer Angriff" } },
    { k: "magicAtkBonus",    label: { en: "Magic Attack Bonus",             de: "Bonus magischer Angriff" } },
    { k: "critChance",       label: { en: "Chance of Critical Hit",         de: "Chance auf kritischen Treffer" } },
    { k: "piercingHit",      label: { en: "Chance for Piercing Hits",       de: "Chance auf durchbohrenden Treffer" } },
    { k: "resCrit",          label: { en: "Critical Hit Resistance",        de: "Widerstand kritischer Treffer" } },
    { k: "resPierce",        label: { en: "Piercing Hit Resistance",        de: "Widerstand durchbohrender Treffer" } },
  ],

  elemental: [
    { k: "magicResistance", label: { en: "Magic Resistance",     de: "Magiewiderstand" } },
    { k: "antiMagic",       label: { en: "Anti-Magic",           de: "Anti-Magie" } },
    { k: "resLightning",    label: { en: "Lightning Resistance", de: "Blitzwiderstand" } },
    { k: "resFire",         label: { en: "Fire Resistance",      de: "Feuerwiderstand" } },
    { k: "resIce",          label: { en: "Ice Resistance",       de: "Eiswiderstand" } },
    { k: "resWind",         label: { en: "Wind Resistance",      de: "Windwiderstand" } },
    { k: "resEarth",        label: { en: "Earth Resistance",     de: "Erdwiderstand" } },
    { k: "resDark",         label: { en: "Darkness Resistance",  de: "Widerstand gegen Dunkelheit" } },
    { k: "powLightning",    label: { en: "Power of Lightning",   de: "Kraft des Blitzes" } },
    { k: "powFire",         label: { en: "Power of Fire",        de: "Kraft des Feuers" } },
    { k: "powIce",          label: { en: "Power of Ice",         de: "Kraft des Eises" } },
    { k: "powWind",         label: { en: "Power of Wind",        de: "Kraft des Windes" } },
    { k: "powEarth",        label: { en: "Power of Earth",       de: "Kraft der Erde" } },
    { k: "powDark",         label: { en: "Power of Darkness",    de: "Kraft der Dunkelheit" } },
  ],

  classBonuses: [
    { k: "bonusWarrior", label: { en: "Bonus against Warriors", de: "Bonus gegen Krieger" } },
    { k: "bonusNinja",   label: { en: "Bonus against Ninjas",   de: "Bonus gegen Ninjas" } },
    { k: "bonusSura",    label: { en: "Bonus against Suras",    de: "Bonus gegen Suras" } },
    { k: "bonusShaman",  label: { en: "Bonus against Shamans",  de: "Bonus gegen Schamaninnen" } },
    { k: "bonusLycan",   label: { en: "Bonus against Lycans",   de: "Bonus gegen Lykaner" } },
    { k: "parryWarrior", label: { en: "Parry Warrior Attack",   de: "Parade Krieger-Angriff" } },
    { k: "parryNinja",   label: { en: "Parry Ninja Attack",     de: "Parade Ninja-Angriff" } },
    { k: "parrySura",    label: { en: "Parry Sura Attack",      de: "Parade Sura-Angriff" } },
    { k: "parryShaman",  label: { en: "Parry Shaman Attack",    de: "Parade Schamanen-Angriff" } },
    { k: "parryLycan",   label: { en: "Parry Lycan Attack",     de: "Parade Lykaner-Angriff" } },
  ],

  weaponDefRupture: [
    { k: "defSword",   label: { en: "Sword Defence",       de: "Schwertverteidigung" } },
    { k: "defTwoHand", label: { en: "Two-Handed Defence",  de: "Zweihandverteidigung" } },
    { k: "defDagger",  label: { en: "Dagger Defence",      de: "Dolchverteidigung" } },
    { k: "defBell",    label: { en: "Bell Defence",        de: "Glockenverteidigung" } },
    { k: "defFan",     label: { en: "Fan Defence",         de: "Fächerverteidigung" } },
    { k: "defClaw",    label: { en: "Claw Defence",        de: "Abwehrchance gegen Krallen" } },
    { k: "defArrow",   label: { en: "Arrow Defence",       de: "Pfeilwiderstand" } },
    { k: "rupSword",   label: { en: "Sword Penetration",   de: "Durchbruch gegen Schwert" } },
    { k: "rupTwoHand", label: { en: "Two-Hand Penetration",de: "Durchbruch gegen Zweihand" } },
    { k: "rupDagger",  label: { en: "Dagger Penetration",  de: "Durchbruch gegen Dolch" } },
    { k: "rupBell",    label: { en: "Bell Penetration",    de: "Durchbruch gegen Glocke" } },
    { k: "rupFan",     label: { en: "Fan Penetration",     de: "Durchbruch gegen Fächer" } },
    { k: "rupClaw",    label: { en: "Claw Penetration",    de: "Durchbruch gegen Krallen" } },
    { k: "rupArrow",   label: { en: "Arrow Penetration",   de: "Durchbruch gegen Pfeile" } },
  ],

  otherBonuses: [
    { k: "blockAttack",  label: { en: "Chance to block attack",         de: "Chance Nahkampf-Angriff abzublocken" } },
    { k: "breakthrough", label: { en: "Block Penetration",              de: "Blockdurchdringung" } },
    { k: "dodgeArrows",  label: { en: "Chance to avoid arrows",         de: "Chance Pfeilangriff auszuweichen" } },
    { k: "accuracy",     label: { en: "Accuracy",                       de: "Präzision" } },
  ],

  hidden: [
    { k: "atkFromCommand",    label: { en: "Attack Value from Command",     de: "Angriffswert durch Kommando" } },
    { k: "dmgBonus",          label: { en: "Damage Bonus",                  de: "Schaden (Bonus)" } },
    { k: "bossDmgAtk",        label: { en: "Damage against Bosses (Attack)",de: "Angriffsschaden gegen Bosse" } },
    { k: "bossDmgSkill",      label: { en: "Damage against Bosses (Skill)", de: "Fertigkeitsschaden gegen Bosse" } },
    { k: "atkBlocking",       label: { en: "Attack Blocking",               de: "Angriffsblockade" } },
    { k: "res90Hp",           label: { en: "Resistance below 90% HP",       de: "Widerstand bei 90% TP" } },
    { k: "defBiologist",      label: { en: "Defence (Biologist)",           de: "Verteidigung (Biologe)" } },
    { k: "empirePenalty",     label: { en: "Empire Penalty",                de: "Königreichs-Abzug" } },
    { k: "tigersStrength",    label: { en: "Tiger's Strength",              de: "Tigerstärke" } },
    { k: "whiteDragonElixir", label: { en: "White Dragon Elixir",           de: "Weißdrachen-Elixier" } },
    { k: "steelDragonElixir", label: { en: "Steel Dragon Elixir",           de: "Stahldrachen-Elixier" } },
    { k: "gradeBonus",        label: { en: "Grade Bonus",                   de: "Grad-Bonus" } },
  ],

  marriage: [
    { k: "lovePoints",      label: { en: "Love Points",        de: "Liebespunkte" } },
    { k: "harmonyBracelet", label: { en: "Harmony Bracelet",   de: "Harmonie-Armband" } },
    { k: "loveNecklace",    label: { en: "Love Necklace",      de: "Liebes-Halskette" } },
    { k: "harmonyNecklace", label: { en: "Harmony Necklace",   de: "Harmonie-Halskette" } },
    { k: "loveEarrings",    label: { en: "Love Earrings",      de: "Liebes-Ohrringe" } },
    { k: "harmonyRings",    label: { en: "Harmony Rings",      de: "Harmonie-Ringe" } },
  ],

  mountPoly: [
    { k: "mounted",     label: { en: "Mounted",                de: "Beritten" }, type: "bool" },
    { k: "ridingSkill", label: { en: "Riding Skill (0–40)",    de: "Reitfertigkeit (0–40)" } },
    { k: "polymorph",   label: { en: "Polymorph",              de: "Verwandlung" }, type: "bool" },
    { k: "polyLevel",   label: { en: "Polymorph Skill Level",  de: "Verwandlungs-Stufe" } },
  ],
};

// Build empty character with every field defaulted to 0 (or sensible base).
function newCharacter(name) {
  const c = {
    id: "char_" + Math.random().toString(36).slice(2, 9),
    kind: "character",
    name: name || "New Character",
    cls: "warrior_body",
    level: 120,
    str: 90, dex: 48, vit: 48, int: 48,
    hp: 5000,
    wpnType: "sword_2h", wpnPreset: "", wpnMin: 295, wpnMax: 350, wpnMagic: 0, wpnRefine: 9,
  };
  const groups = ["damageDefense", "elemental", "classBonuses", "weaponDefRupture", "otherBonuses", "hidden", "marriage", "mountPoly"];
  for (const g of groups) {
    for (const f of FIELDS[g]) {
      if (c[f.k] !== undefined) continue;
      c[f.k] = f.type === "bool" ? false : 0;
    }
  }
  return c;
}
