// Offline: compute the EXACT optimal computer-leads policy and emit policy.js.
// Keys are generated through game.js oppBelief — the identical path solver.js
// uses at runtime — so the table is guaranteed interoperable.
import { oppBelief, myRemaining, color, arrToMask } from "./game.js";

const N=9, FULL=(1<<N)-1;
const isBlack=(v)=>(v%2)===0;
const pop=(m)=>{let c=0;while(m){c+=m&1;m>>=1;}return c;};
const bits=(m)=>{const a=[];for(let v=0;v<N;v++)if(m&(1<<v))a.push(v);return a;};

// ---- shared key helpers (MUST match solver.js) ----
function gcd(a,b){while(b){[a,b]=[b,a%b];}return a;}
function beliefKey(scenarios){
  let g=0;for(const s of scenarios)g=gcd(g,s.weight);if(g===0)g=1;
  return scenarios.map(s=>[s.remainingMask,s.weight/g]).sort((a,b)=>a[0]-b[0]).map(([m,w])=>m+":"+w).join(",");
}
function stateKey(myMask,scenarios,colStr){return myMask+"|"+beliefKey(scenarios)+"|"+(colStr==="black"?0:1);}

// ---- expectimax value (float belief Map) ----
const memo=new Map();
function bkey(belief){let W=0;for(const[,w]of belief)W+=w;return [...belief.entries()].map(([R,w])=>[R,w/W]).sort((a,b)=>a[0]-b[0]).map(([R,w])=>`${R}:${w.toFixed(7)}`).join(",");}
function V(X,belief){
  if(X===0)return 0;const k=X+"|"+bkey(belief);const c=memo.get(k);if(c!==undefined)return c;
  let W=0;for(const[,w]of belief)W+=w;let value=0;
  for(let col=0;col<2;col++){const E=[];let Pc=0;
    for(const[R,w]of belief){const sz=pop(R);for(const o of bits(R)){if((isBlack(o)?0:1)!==col)continue;const wt=w/sz;E.push([o,R&~(1<<o),wt]);Pc+=wt;}}
    if(Pc===0)continue;let best=-Infinity;
    for(const x of bits(X)){const nX=X&~(1<<x);const b=[new Map(),new Map(),new Map()];const sw=[0,0,0];
      for(const[o,nR,wt]of E){const s=x>o?0:x===o?1:2;sw[s]+=wt;b[s].set(nR,(b[s].get(nR)||0)+wt);}
      let ev=0;const pay=[1,0,-1];for(let s=0;s<3;s++){if(sw[s]===0)continue;ev+=sw[s]*(pay[s]+V(nX,b[s]));}
      ev/=Pc;if(ev>best)best=ev;}
    value+=(Pc/W)*best;}
  memo.set(k,value);return value;
}
function beliefMap(scenarios){const m=new Map();for(const s of scenarios)m.set(s.remainingMask,(m.get(s.remainingMask)||0)+s.weight);return m;}
function bestCard(X,belief,col){
  const E=[];for(const[R,w]of belief){const sz=pop(R);for(const o of bits(R)){if((isBlack(o)?0:1)!==col)continue;E.push([o,R&~(1<<o),w/sz]);}}
  let Pc=0;for(const e of E)Pc+=e[2];
  let bx=-1,bev=-Infinity;
  for(const x of bits(X)){const nX=X&~(1<<x);const b=[new Map(),new Map(),new Map()];const sw=[0,0,0];
    for(const[o,nR,wt]of E){const s=x>o?0:x===o?1:2;sw[s]+=wt;b[s].set(nR,(b[s].get(nR)||0)+wt);}
    let ev=0;const pay=[1,0,-1];for(let s=0;s<3;s++){if(sw[s]===0)continue;ev+=sw[s]*(pay[s]+V(nX,b[s]));}
    ev/=Pc;if(ev>bev+1e-12){bev=ev;bx=x;}}
  return bx;
}

console.error("warming memo…");
V(FULL,new Map([[FULL,1]]));
console.error("memo:",memo.size);

const policy={};
const seen=new Set();
const SIGNS=[["higher",0],["equal",1],["lower",2]];
function enumerate(rounds){
  const state={rounds};
  const X=arrToMask(myRemaining(state));
  if(X===0)return;
  const {scenarios}=oppBelief(state);
  const belief=beliefMap(scenarios);
  const dedup=X+"|"+bkey(belief);
  if(seen.has(dedup))return; seen.add(dedup);
  for(const colStr of ["black","white"]){
    const col=colStr==="black"?0:1;
    // possible only if some scenario has a card of this colour
    const E=[];for(const[R,w]of belief){const sz=pop(R);for(const o of bits(R)){if((isBlack(o)?0:1)!==col)continue;E.push([o,w/sz]);}}
    if(E.length===0)continue;
    const x=bestCard(X,belief,col);
    policy[stateKey(X,scenarios,colStr)]=x;
    // which signs are reachable for this (col,x)?
    const reach=new Set();
    for(const[o]of E){reach.add(x>o?"higher":x===o?"equal":"lower");}
    for(const[res]of SIGNS){if(reach.has(res))enumerate(rounds.concat([{leader:"opp",myCard:x,oppColor:colStr,result:res}]));}
  }
}
enumerate([]);
const json=JSON.stringify(policy);
console.error("entries:",Object.keys(policy).length,"bytes:",json.length);
process.stdout.write("// Auto-generated by buildpolicy.mjs — exact optimal computer-leads policy.\n");
process.stdout.write("// stateKey = myMask|sortedBelief|colour -> optimal card. Do not edit by hand.\n");
process.stdout.write("export default "+json+";\n");
